name: Start autotests

on:
  schedule:
  - cron: "32 11 * * 1-5"

jobs:
    integration-tests:
    # На какой ОС будет работать виртуальная машина
    # Можно выбрать Ubuntu, Windows Server или macOS
    runs-on: ubuntu-latest
    # Шаги действия
    steps:
      # Шаг 1: собираем сервисы в режиме тестирования
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.prod.yml -f docker-compose.test.yml up -d --build
 
      # Шаг 2: собираем проект с тестами
      - name: Build tests
        run: dotnet build GOT.Tests

      # Шаг 3: запускаем тесты с небольшой детализацией
      - name: Run tests
        run: dotnet test LOT.Tests --verbosity normal
